/*
 * ReportGenerator.java - Java Language Engine for EduPulse Academic System
 * Formats official Student Report Cards.
 */

public class ReportGenerator {
    public static void main(String[] args) {
        if (args.length < 5) {
            System.out.println("Error: Usage - java ReportGenerator studentName studentId class gpa attendance");
            return;
        }

        String name = args[0];
        String id = args[1];
        String studentClass = args[2];
        String gpa = args[3];
        String attendance = args[4];

        System.out.println("==========================================");
        System.out.println(" OFFICIAL STUDENT ACADEMIC REPORT CARD");
        System.out.println("==========================================");
        System.out.println("Student Name : " + name);
        System.out.println("Student ID   : " + id);
        System.out.println("Class        : " + studentClass);
        System.out.println("Current GPA  : " + gpa + " / 4.00");
        System.out.println("Attendance   : " + attendance + "%");
        System.out.println("Status       : GENERATED BY JAVA REPORT ENGINE");
        System.out.println("==========================================");
    }
}
